name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Desktop/Web, based on GoogleWebRTC.
version: 1.0.0
homepage: https://github.com/cloudwebrtc/flutter-webrtc
environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  collection: 1.19.1
  dart_webrtc: 1.5.3+hotfix.5
  flutter:
    sdk: flutter
  path_provider: 2.1.5
  web: 1.1.1
  webrtc_interface: ^1.2.2+hotfix.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: 6.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
      elinux:
        pluginClass: FlutterWebRTCPlugin
